trunk/Force4Facebook-depricated/src/objects/FacebookApp__c.object
<CustomObject>
    <fields>
        <fullName>AppKey__c</fullName>
        <label>App Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AppSecret__c</fullName>
        <label>App Secret</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FBUserId__c</fullName>
        <label>FBUserId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Facebook App</label>
    <nameField>
        <label>App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facebook Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/Force4Facebook-depricated/src/classes/FBToolkitPageController.cls
public class FBToolkitPageController {
	
	public FacebookApp__c fbc { 
		get { 
			System.debug(LoggingLevel.INFO, '\n\nReturning fbc from getter.\nfbc: \n\n' + FacebookConnection.fbApp + '\n\n');
			return FacebookConnection.fbApp; 
		} 
		set; 
	}
	public FacebookConnection fbConnection { get; set; }
	public List<String> friendsList { get { return FacebookConnection.friendsList; } set; }
	public String fbUserId { get; set; }
	
	public FBToolkitPageController() {
    	System.debug(LoggingLevel.INFO, '\n\nFBToolkitPageController constructor()\n');
		if (FacebookConnection.fbApp != null) {
			System.debug(LoggingLevel.INFO, FacebookConnection.fbApp.AppKey__c);	
			System.debug(LoggingLevel.INFO, FacebookConnection.fbApp.AppSecret__c);
			System.debug(LoggingLevel.INFO, FacebookConnection.fbApp.FBUserId__c);
			fbc = FacebookConnection.fbApp;
			fbUserId = fbc.FBUserID__c;
		}
	}
    public String getFormContent() {
    	System.debug(LoggingLevel.INFO, '\n\nFBToolkitPageController getFormContent()\n');
        return '<fb:req-choice url=\'see wiki page for fb:req-choice for details.\' label=\'Ignore the Connect test app!\' />';
    }
    public PageReference getUserInfo() {
    	System.debug(LoggingLevel.INFO, '\n\nFBToolkitPageController getUserInfo	()\n');
        return null;
    }
	
}