trunk/Force4Facebook-depricated/src/objects/FacebookApp__c.object
<CustomObject>
    <fields>
        <fullName>AppKey__c</fullName>
        <label>App Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AppSecret__c</fullName>
        <label>App Secret</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FBUserId__c</fullName>
        <label>FBUserId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Facebook App</label>
    <nameField>
        <label>App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facebook Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/Force4Facebook/src/classes/FacebookTestPageController.cls
public class FacebookTestPageController {
	
	public FacebookApp__c fbc { get; set; }
	public String fbUserId { get; set; }
	
	public List<String> debugStatements {
		get {
			if (debugStatements == null) {
				debugStatements = new List<String>();
			}
			return debugStatements;
		}
		set; 
	}
	public void debug(String value) {
		debugStatements.add(value + '\n'); 
	}
	
	public FacebookTestPageController() {
		System.debug(LoggingLevel.INFO, '\n\nFacebookTestPageController\n' + FacebookConnection.fbApp + '\nconnection???');
		if (FacebookConnection.fbApp != null) {
			debug(FacebookConnection.fbApp.AppKey__c);	
			debug(FacebookConnection.fbApp.AppSecret__c);
			debug(FacebookConnection.fbApp.FBUserId__c);
			fbc = FacebookConnection.fbApp;
			fbUserId = fbc.FBUserID__c;
		}
	}	
}