trunk/Force4Facebook-depricated/src/objects/FacebookApp__c.object
<CustomObject>
    <fields>
        <fullName>AppKey__c</fullName>
        <label>App Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AppSecret__c</fullName>
        <label>App Secret</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FBUserId__c</fullName>
        <label>FBUserId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Facebook App</label>
    <nameField>
        <label>App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facebook Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/Force4Facebook/src/objects/FacebookAppList__c.object
<CustomObject>
    <fields>
        <fullName>AppKey__c</fullName>
        <label>AppKey</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AppSecret__c</fullName>
        <label>AppSecret</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>app_id__c</fullName>
        <label>app_id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>canvas_name__c</fullName>
        <label>canvas_name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>company_name__c</fullName>
        <label>company_name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>daily_active_users__c</fullName>
        <label>daily_active_users</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>display_name__c</fullName>
        <label>display_name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>icon_url__c</fullName>
        <label>icon_url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>logo_url__c</fullName>
        <label>logo_url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>monthly_active_users__c</fullName>
        <label>monthly_active_users</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>weekly_active_users__c</fullName>
        <label>weekly_active_users</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>FacebookAppList</label>
    <nameField>
        <label>FacebookAppList Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FacebookAppLists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/Force4Facebook-depricated/src/classes/FutureMethods.cls
global class FutureMethods {

	private static void addNewApp(String name, String uid, String app_key, String app_secret) {
		System.debug(LoggingLevel.INFO, '\n\nIn the set keys future method.\n');
		FacebookApp__c fbApp = new FacebookApp__c(Name=name, FBUserId__c=uid, AppKey__c=app_key, AppSecret__c=app_secret);
		insert fbApp;
	} 
	
	@future(callout=true)
	public static void getAppData(List<String> ids) {
		List<FacebookAppList__c> apps = new List<FacebookAppList__c>();
		for (String id : ids) {
			FacebookAppList__c appList = [Select Id, AppKey__c, AppSecret__c, Name From FacebookAppList__c Where Id = :id];
			FacebookSession session = new FacebookSession(appList.AppKey__c, appList.AppSecret__c, '', '');
			FacebookPublicApplicationInfo pai = session.getAppPublicInfo(appList.AppKey__c);
			appList.app_id__c = pai.app_id;
			appList.canvas_name__c = pai.canvas_name;
			appList.company_name__c = pai.company_name;
			appList.daily_active_users__c = Integer.valueOf(pai.daily_active_users);
			appList.description__c = pai.description;
			appList.display_name__c = pai.display_name;
			appList.icon_url__c = pai.icon_url;
			appList.logo_url__c = pai.logo_url;
			appList.monthly_active_users__c = Integer.valueOf(pai.monthly_active_users);
			appList.weekly_active_users__c = Integer.valueOf(pai.weekly_active_users);
			apps.add(appList);
		}
		update apps;
	}
}