trunk/force4facebook3_use_branches-force4facebook3_toolkit/src/objects/SiteConfig__c.object
<CustomObject>
    <fields>
        <fullName>APIKey__c</fullName>
        <label>API Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FacebookAppSecret__c</fullName>
        <label>Facebook App Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewPortalUserAccount__c</fullName>
        <label>New Portal User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Site Configs</relationshipLabel>
        <relationshipName>Site_Configs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site Config</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/Force4Facebook2-depricated/src/classes/MyFacebookSiteHeaderController.cls
public with sharing class MyFacebookSiteHeaderController {


    public SiteConfig__c siteConfig; 

    public SiteConfig__c getSiteConfig() {
    	if (siteConfig == null) {
    		System.debug('\n\nLooking up site config using ' + Site.getName() + '\n\n');
	    	List<SiteConfig__c> configs = [Select Id, Name, FacebookAppSecret__c, APIKey__c, NewPortalUserAccount__c From SiteConfig__c Where Name = :Site.getName() Limit 1];
    		if (configs.size() == 1) {
    			siteConfig = configs.get(0);
    		} else {
    			return null;
    		}
    	}
    	return siteConfig;
    }

	public MyFacebookSiteHeaderController() {
		getSiteConfig();
	}
}